# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\"\x84\x02\n\x07ImuData\x12\x11\n\ttimestamp\x18\x01 \x01(\x11\x12\x12\n\naccel_x_mg\x18\x02 \x01(\x11\x12\x12\n\naccel_y_mg\x18\x03 \x01(\x11\x12\x12\n\naccel_z_mg\x18\x04 \x01(\x11\x12\x13\n\x0bgyro_x_mdps\x18\x05 \x01(\x11\x12\x13\n\x0bgyro_y_mdps\x18\x06 \x01(\x11\x12\x13\n\x0bgyro_z_mdps\x18\x07 \x01(\x11\x12\x17\n\x0fgyro_data_valid\x18\x08 \x01(\x08\x12\x18\n\x10\x61\x63\x63\x65l_data_valid\x18\t \x01(\x08\"8\n\nFilterMode\x12\x12\n\x0eIMU_UNFILTERED\x10\x00\x12\x16\n\x12IMU_MOVING_AVERAGE\x10\x01\"\xda\x02\n\x07GpsData\x12\x1e\n\x04time\x18\x01 \x01(\x0b\x32\x10.GpsData.UtcTime\x12\x1e\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x10.GpsData.UtcDate\x12\x14\n\x0clat_microdeg\x18\x03 \x01(\x11\x12\x14\n\x0clon_microdeg\x18\x04 \x01(\x11\x12\x13\n\x0b\x61ltitude_mm\x18\x05 \x01(\x11\x12\x12\n\nspeed_mkts\x18\x06 \x01(\x11\x12\x12\n\ncourse_deg\x18\x07 \x01(\x11\x12\x0f\n\x07quality\x18\x08 \x01(\x11\x12\x10\n\x08num_sats\x18\t \x01(\x11\x12\x12\n\ndata_valid\x18\n \x01(\x08\x1a:\n\x07UtcTime\x12\r\n\x05hours\x18\x01 \x01(\r\x12\x0f\n\x07minutes\x18\x02 \x01(\r\x12\x0f\n\x07seconds\x18\x03 \x01(\r\x1a\x33\n\x07UtcDate\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMUDATA._serialized_start=22
  _IMUDATA._serialized_end=282
  _IMUDATA_FILTERMODE._serialized_start=226
  _IMUDATA_FILTERMODE._serialized_end=282
  _GPSDATA._serialized_start=285
  _GPSDATA._serialized_end=631
  _GPSDATA_UTCTIME._serialized_start=520
  _GPSDATA_UTCTIME._serialized_end=578
  _GPSDATA_UTCDATE._serialized_start=580
  _GPSDATA_UTCDATE._serialized_end=631
# @@protoc_insertion_point(module_scope)
